version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./infra/local/docker/Dockerfile
    volumes:
      - ./:/app
      - ./docker/php/prod.ini:/usr/local/etc/php/conf.d/prod.ini
    working_dir: /app
    depends_on:
      - postgres
    networks:
      - bank-bridge
  web:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./infra/local/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - postgres
      - cache
    networks:
      - bank-bridge
  postgres:
      image: postgres:15.2
      restart: unless-stopped
      ports:
        - "5432:5432"
      networks:
        - bank-bridge
      environment:
          POSTGRES_DATABASE: ${DB_PASSWORD}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_USER: ${DB_USERNAME}
  postgres-tests:
      image: postgres:15.2
      restart: unless-stopped
      networks:
        - bank-bridge
      environment:
          POSTGRES_DATABASE: ${DB_PASSWORD}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_USER: ${DB_USERNAME}
  cache:
    image: redis:7
    networks:
      - bank-bridge
    ports:
        - "6379:6379"

networks:
  bank-bridge:
    driver: bridge
